stages:
  - check
  - build
  - test
  - deploy

.rust-default:
  image: gitlab.lrz.de:5005/quantum-research/tetra:latest
  before_script:
    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)
    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    
    ## Collect SSH RSA public key from gitlab and add them to the known_hosts file
    ## 
    - ssh-keyscan -H gitlab.lrz.de >> ~/.ssh/known_hosts
    - source "$HOME/.cargo/env"

default:
  tags:
    - kubernetes

check:clippy:
  stage: check
  extends: .rust-default
  script:
    - cargo clippy --color always --workspace --all-features --all-targets --no-deps -- -Dwarnings
  allow_failure: true

check:fmt:
  stage: check
  extends: .rust-default
  script:
    - cargo fmt -- --check --color always
  allow_failure: true

build:
  stage: build
  extends: .rust-default
  script:
    # Report on the used Rust version
    - rustc --version

    # Build the project
    - cargo build -vv --color always

  artifacts:
    paths:
      - target/debug
    expire_in: 1 hour

build:docs:
  stage: build
  extends: .rust-default
  script:
    - cargo doc --color always --no-deps
  artifacts:
    paths:
      - target/doc
    expire_in: 1 day

test:
  stage: test
  extends: .rust-default
  needs:
    - build
  script:
    - cargo test --color always --workspace --no-fail-fast

pages:
  stage: deploy
  image: alpine:latest
  needs:
    - test
    - build:docs
  dependencies:
    - test
    - build:docs
  script:
    - mv target/doc public/
    - echo '<meta http-equiv="refresh" content="0; url=tetra">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - main